export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Navigation from "@/components/navigation/Navigation"
import "./globals.css"
import BackgroundImage from "@/components/BackgroundImage"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main>{children}</main>
      </body>
    </html>
  )
}
